#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.3.5~bpo9+1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'certbot.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.3.5~bpo9+1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'certbot.service' 'certbot.timer' >/dev/null || true
fi
# End automatically added section
