#!/bin/bash

#script for enabeling firewall rules in iptables. this is for IPv4 en IPv6
#Arne Van de Bemdt

#flush existing rules, go back to default
iptables -F
ip6tables -F

#open ports for incomming connection IPv4
iptables -A INPUT -p tcp --dport 20 -j ACCEPT
iptables -A INPUT -p tcp --dport 21 -j ACCEPT
iptables -A INPUT -p tcp --dport 25 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A INPUT -p tcp --dport 587 -j ACCEPT
iptables -A INPUT -p tcp --dport 993 -j ACCEPT
iptables -A INPUT -p tcp --dport 22345 -j ACCEPT






